# List of champions to pick from in order of preference
picks = [
    "Katarina",
    "Yone", 
    "Veigar",
    "Lee Sin",
]

# List of champions to ban in order of preference 
bans = [
    "Teemo",
    "Annie",
    "Ashe", 
    "Master Yi",
    "Garen",
]
